### ISSUE TITLE
NPE with MongoDB connector in Swan Lake - Alpha 5

### ISSUE THREAD

**Issue by maheeka** [ballerina-platform/module-ballerinax-mongodb#94]
**Description:**
When  running an existing code that was built with MongoDB connector  in slalpha4 on slalpha5, it  fails with NPE

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
slalpha5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Run the sample in https://swanlake.central.ballerina.io/ballerinax/mongodb
Following stack trace can be observed.
```
[2021-05-01 23:14:34,231] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.Desugar.desugarObjectTypeInit(Desugar.java:6237)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:6222)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangTypeInit.accept(BLangTypeInit.java:62)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:7781)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1350)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1479)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7797)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7807)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1473)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7797)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:3359)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangMatch.accept(BLangMatch.java:100)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7797)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7807)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1473)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7797)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7469)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangStatementExpression.accept(BLangStatementExpression.java:50)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:7781)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visitCheckAndCheckPanicExpr(Desugar.java:7421)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:7366)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangCheckPanickedExpr.accept(BLangCheckPanickedExpr.java:44)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:7781)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1350)
	at org.wso2.ballerinalang.compiler.tree.BLangSimpleVariable.accept(BLangSimpleVariable.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1479)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangSimpleVariableDef.accept(BLangSimpleVariableDef.java:46)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7797)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:7807)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1246)
	at org.wso2.ballerinalang.compiler.tree.BLangBlockFunctionBody.accept(BLangBlockFunctionBody.java:58)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:1291)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:73)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7814)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:803)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:167)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:7756)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:457)
	at io.ballerina.projects.internal.CompilerPhaseRunner.desugar(CompilerPhaseRunner.java:249)
	at io.ballerina.projects.internal.CompilerPhaseRunner.performBirGenPhases(CompilerPhaseRunner.java:158)
	at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:397)
	at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
	at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
	at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:147)
	at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:133)
	at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:107)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:152)
	at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:106)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:69)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:166)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Related Issues:**

**Comment by kasthuriraajan** [comment]
This issue is no more in the newer versions. We can close this issue.
